server:
  port: ":3000"

db:
  host: pgvector
  port: 5432
  user: postgres
  password: 1234
  name: vectordb

# server:
#   port: ":3000"

# db:
#   host: localhost
#   port: 5433
#   user: postgres
#   password: 1234
#   name: vectordb


# server:
#   port: ":3000"

# db:
#   host: pgvector
#   port: 5432
#   user: postgres
#   password: 1234
#   name: vectordb
